config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks" 
  }
  resources :users ,   only: [:show] do
    member do
     get :liking, :likers
    end
  end
  resources :likes,    only: [:create, :destroy]
  resources :profiles, only: [:show,:edit,:update]
  resources :message, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :liking, class_name: "User"
  belongs_to :liker, class_name: "User"
  validates :liking_id, presence: true
  validates :liker_id, presence:true
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         has_many :likes,dependent: :destroy
  mount_uploader :image, ImageUploader

  paginates_per 16

  has_many :liking_likes, foreign_key: "liker_id", class_name: "Like", dependent: :destroy
  has_many :likings, through: :liking_likes
    has_many :liker_likes, foreign_key: "liking_id", class_name: "Like", dependent: :destroy
  has_many :likers, through: :liker_likes

  def liking?(other_user)
    liking_likes.find_by(liking_id: other_user.id)
  end

  def like!(other_user)
    liking_likes.create!(liking_id: other_user.id)
  end

  def unlike!(other_user)
    liking_likes.find_by(liking_id: other_user.id).destroy
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        name:     auth.info.name
      )
      user.remote_image_url = auth.info.image.gsub('http://','https://')
      user.save
    end
    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:like][:liking_id])
    current_user.like!(@user)
    redirect_to root_path
  end

  def destroy
    @user = Like.find(params[:id]).liking
    current_user.unlike!(@user)
    redirect_to root_path
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController

  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find_by(id: current_user.id)
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = current_user.update(profile_params)
    redirect_to profile_path
  end

  private
  def profile_params
    params.require(:user).permit!
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find_by(id: current_user.id)
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = current_user.update(profile_params)
    redirect_to profile_path
  end

  private
  def profile_params
    params.require(:user).permit!
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @profile = User.find_by(id: current_user.id)
    if current_user.sexes == 1
      @searches = User.where(sexes: 2).page(params[:page])
    else
      @searches = User.where(sexes: 1).page(params[:page])
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.likings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.likers
    render 'show_follower'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

end

# class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
#   def facebook
#     callback_from :facebook
#   end
#   private

#   def callback_from(provider)
#     @user = User.from_omniauth(request.env['omniauth.auth'])

#     if @user.persisted?
#       flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
#       sign_in_and_redirect @user, event: :authentication
#     else
#       session["devise.facebook_data"] = request.env['omniauth.auth']
#       redirect_to new_user_registration_url
#     end
#   end

#   def failure
#     redirect_to root_path
#   end
# end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

  def following
      @user  = User.find(params[:id])
      @users = @user.likings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.likers
    render 'show_follower'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pairs
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/message/index.haml
=render 'shared/header'
=render 'shared/side'
.wrapper
  =render 'message/index'
  =render 'shared/footer'

app/views/profiles/_user_profile.haml
.ui-view
  .main.box_mypage_view.contents_padding
    .banner
      %p.banner__message バナーだよ
    .box_search_menu
      .button_search_setting.float_left
        %a.button_b.button_white_a 
          %span.search プロフィールの見え方を確認
      %nav.box_change_view_tabs
        %ul.change_view_tabs
          %li.tab_item.tab_item01.is_current
          %li.tab_item.tab_item02
      .button_search_setting.float_right
        %a.button_b.button_white_a.pairs_new
          %span.news.fa.fa-lightbulb-o Pairsからのお知らせ
    .box_mypage_detail
      .box_mypage_detail_inner01
        .mypage_detail_inner_left
          .user_status
            .user_status_title
              %p 会員ステータス
              %a.button_status_conf.button_f.button_white_a 確認
            %p.user_status_label 無料会員
          .user_tweet
            .user_tweet_title
              %p つぶやき
            .user_tweet_inner
              .user_tweet_inner
                .user_tweet_textarea
                  %p.user_tweet_textarea ここにツイートしてね
          .visiter_summary
            %p.visiter_summary_title 足跡
            .visiter_summary_count
              %p.text 過去１週間の足跡
              %p.count 
                %em１６
                人
            %ul.user_list
              %li.user_item
                %a
                  %img.image-circle 
                  %p.user_info 名前
                  %p.user_time 時間
            .box_link_more
              %a.button_f.button_white_a もっと見る
        .mypage_detail_inner_right
          .box_my_display_photo
            .my_summary_info
              =image_tag current_user.image,size: "390x390"
            .box_my_photo
            .box_my_photo_pager
              %a.pager_pre.button_c.button_white_a 前の4枚
              %a.pager_next.button_c.button_white_a 次の４枚
      .box_mypage_detail_inner02
        .mypage_detail_inner_left
          .box_profile_detail
            %p.detail_sub_note=link_to "編集はこちら", edit_profile_path(@user.id)
            %p.detail_sub_title
              %span.title_a Pairsプロフ
            %dl.detail_item_list
              %dt.detail_item_title 
                %span.item_title 身長
              %dd.detail_item_value= @user.height
              %dt.detail_item_title 
                %span.item_title 体型
              %dd.detail_item_value= @user.bodytype
              %dt.detail_item_title
                %span.item_title 血液型
              %dd.detail_item_value= @user.blood
              %dt.detail_item_title
                %span.item_title 居住区
              %dd.detail_item_value= @user.live
              %dt.detail_item_title 
                %span.item_title 出身地
              %dd.detail_item_value= @user.birthplace
              %dt.detail_item_title 
                %span.item_title 職種
              %dd.detail_item_value= @user.job
              %dt.detail_item_title 
                %span.item_title 学歴
              %dd.detail_item_value= @user.education
              %dt.detail_item_title
                %span.item_title 年収
              %dd.detail_item_value= @user.income
              %dt.detail_item_title 
                %span.item_title タバコ
              %dd.detail_item_value= @user.tobacco
            %p.detail_sub_title
              %span.title_a 詳細プロフ
            %p.detail_sub_title 基本情報
            %dl.detail_item_list
              %dt.detail_item_title 
                %span.item_title ニックネーム
              %dd.detail_item_value= @user.nickname
              %dt.detail_item_title 
                %span.item_title 年齢
              %dd.detail_item_value= @user.age
              %dt.detail_item_title 
                %span.item_title 兄弟姉妹
              %dd.detail_item_value= @user.brother
              %dt.detail_item_title 
                %span.item_title 国籍
              %dd.detail_item_value= @user.country
              %dt.detail_item_title 
                %span.item_title 話せる言語
              %dd.detail_item_value= @user.language
            %p.detail_sub_title 恋愛・結婚について
            %dl.detail_item_list
              %dt.detail_item_title 
                %span.item_title 結婚歴
              %dd.detail_item_value= @user.marital
              %dt.detail_item_title 
                %span.item_title 子供の有無
              %dd.detail_item_value= @user.children
              %dt.detail_item_title 
                %span.item_title 結婚に対する意思
              %dd.detail_item_value= @user.marriagedesire
              %dt.detail_item_title 
                %span.item_title 子供が欲しいか
              %dd.detail_item_value= @user.wantchild
              %dt.detail_item_title 
                %span.item_title 家事・育児
              %dd.detail_item_value= @user.household
              %dt.detail_item_title 
                %span.item_title 出会うまでの希望
              %dd.detail_item_value= @user.meet
              %dt.detail_item_title 
                %span.item_title 初回デート費用
              %dd.detail_item_value= @user.datecost
            %p.detail_sub_title 性格・趣味・生活
            %dl.detail_item_list
              %dt.detail_item_title 
                %span.item_title 性格・タイプ
              %dd.detail_item_value= @user.personality
              %dt.detail_item_title 
                %span.item_title 社交性
              %dd.detail_item_value= @user.sociability
              %dt.detail_item_title 
                %span.item_title 同居人
              %dd.detail_item_value= @user.housemate
              %dt.detail_item_title 
                %span.item_title 休日
              %dd.detail_item_value= @user.holiday
              %dt.detail_item_title 
                %span.item_title お酒
              %dd.detail_item_value= @user.liquor
              %dt.detail_item_title 
                %span.item_title 好きなこと・趣味
              %dd.detail_item_value= @user.hobby
          %a.button_b.button_white_a 
            %span 質問付きいいね！の設定
        .mypage_detail_inner_right
          .box_join_community
            .join_community_title_b
              %span.title_a 参加しているコミュニティ
              %a.button_b.button_white_a.button_new_entry 新しいコミュニティに入る
            %ul.join_community_list
              %li.join_community_item
                %a
                  .box_community_item_img
                    %p image画像
                  %p.community_item_title ペンタトニックスが好き
                  %p.community_item_count 276人
            .box_community_pager
              %a.pager_pre.button_c.button_white_a.fa.fa-chevron-left
              %a.pager_next.button_c.button_white_a.fa.fa-chevron-right
          .box_mypage_introduction
            %p.introduction_title 自己紹介文
            %p.introduction_note 自己紹介文を充実させると、マッチング１０倍UP!!
            %p.introduction_text 本文

app/views/profiles/_user_profile_edit.haml
.ui-view
  .main.box_mypage_view.contents_padding
    .banner
      %p.banner__message バナーだよ
    .box_search_menu
      .button_search_setting.float_left
        %a.button_b.button_white_a 
          %span.search プロフィールの見え方を確認
      %nav.box_change_view_tabs
        %ul.change_view_tabs
          %li.tab_item.tab_item01.is_current
          %li.tab_item.tab_item02
      .button_search_setting.float_right
        %a.button_b.button_white_a.pairs_new
          %span.news.fa.fa-lightbulb-o Pairsからのお知らせ
    .box_mypage_detail
      .box_mypage_detail_inner01
        .mypage_detail_inner_left
          .user_status
            .user_status_title
              %p 会員ステータス
              %a.button_status_conf.button_f.button_white_a 確認
            %p.user_status_label 無料会員
          .user_tweet
            .user_tweet_title
              %p つぶやき
            .user_tweet_inner
              .user_tweet_inner
                .user_tweet_textarea
                  %p.user_tweet_textarea ここにツイートしてね
          .visiter_summary
            %p.visiter_summary_title 足跡
            .visiter_summary_count
              %p.text 過去１週間の足跡
              %p.count 
                %em１６
                人
            %ul.user_list
              %li.user_item
                %a
                  %img.image-circle 
                  %p.user_info 名前
                  %p.user_time 時間
            .box_link_more
              %a.button_f.button_white_a もっと見る
        .mypage_detail_inner_right
          .box_my_display_photo
            .my_summary_info
            .box_my_photo
            .box_my_photo_pager
              %a.pager_pre.button_c.button_white_a 前の4枚
              %a.pager_next.button_c.button_white_a 次の４枚
      .box_mypage_detail_inner02
        .mypage_detail_inner_left
          .box_profile_detail
            =form_for @user ,:url => {:action => :update} do |f|
              %p.detail_sub_note この項目を押すと編集できます。
              %p.detail_sub_title
                %span.title_a Pairsプロフ
              %dl.detail_item_list
                %dt.detail_item_title 
                  %span.item_title 身長
                %dd.detail_item_value= f.text_field :height,autofocus: true
                %dt.detail_item_title 
                  %span.item_title 体型
                %dd.detail_item_value= f.text_field :bodytype
                %dt.detail_item_title
                  %span.item_title 血液型
                %dd.detail_item_value= f.text_field :blood
                %dt.detail_item_title
                  %span.item_title 居住区
                %dd.detail_item_value= f.text_field :live
                %dt.detail_item_title 
                  %span.item_title 出身地
                %dd.detail_item_value= f.text_field :birthplace
                %dt.detail_item_title 
                  %span.item_title 職種
                %dd.detail_item_value= f.text_field :job
                %dt.detail_item_title 
                  %span.item_title 学歴
                %dd.detail_item_value= f.text_field :education
                %dt.detail_item_title
                  %span.item_title 年収
                %dd.detail_item_value= f.text_field :income
                %dt.detail_item_title 
                  %span.item_title タバコ
                %dd.detail_item_value= f.text_field :tobacco
              %p.detail_sub_title
                %span.title_a 詳細プロフ
              %p.detail_sub_title 基本情報
              %dl.detail_item_list
                %dt.detail_item_title 
                  %span.item_title ニックネーム
                %dd.detail_item_value= f.text_field :nickname
                %dt.detail_item_title 
                  %span.item_title 年齢
                %dd.detail_item_value= f.text_field :age
                %dt.detail_item_title 
                  %span.item_title 兄弟姉妹
                %dd.detail_item_value= f.text_field :brother
                %dt.detail_item_title 
                  %span.item_title 国籍
                %dd.detail_item_value= f.text_field :country
                %dt.detail_item_title 
                  %span.item_title 話せる言語
                %dd.detail_item_value= f.text_field :language
              %p.detail_sub_title 恋愛・結婚について
              %dl.detail_item_list
                %dt.detail_item_title 
                  %span.item_title 結婚歴
                %dd.detail_item_value= f.text_field :marital
                %dt.detail_item_title 
                  %span.item_title 子供の有無
                %dd.detail_item_value= f.text_field :children
                %dt.detail_item_title 
                  %span.item_title 結婚に対する意思
                %dd.detail_item_value= f.text_field :marriagedesire
                %dt.detail_item_title 
                  %span.item_title 子供が欲しいか
                %dd.detail_item_value= f.text_field :wantchild
                %dt.detail_item_title 
                  %span.item_title 家事・育児
                %dd.detail_item_value= f.text_field :household
                %dt.detail_item_title 
                  %span.item_title 出会うまでの希望
                %dd.detail_item_value= f.text_field :meet
                %dt.detail_item_title 
                  %span.item_title 初回デート費用
                %dd.detail_item_value= f.text_field :datecost
              %p.detail_sub_title 性格・趣味・生活
              %dl.detail_item_list
                %dt.detail_item_title 
                  %span.item_title 性格・タイプ
                %dd.detail_item_value= f.text_field :personality
                %dt.detail_item_title 
                  %span.item_title 社交性
                %dd.detail_item_value= f.text_field :sociability
                %dt.detail_item_title 
                  %span.item_title 同居人
                %dd.detail_item_value= f.text_field :housemate
                %dt.detail_item_title 
                  %span.item_title 休日
                %dd.detail_item_value= f.text_field :holiday
                %dt.detail_item_title 
                  %span.item_title お酒
                %dd.detail_item_value= f.text_field :liquor
                %dt.detail_item_title 
                  %span.item_title 好きなこと・趣味
                %dd.detail_item_value= f.text_field :hobby
                = f.submit "Save"
          %a.button_b.button_white_a 
            %span 質問付きいいね！の設定
        .mypage_detail_inner_right
          .box_join_community
            .join_community_title_b
              %span.title_a 参加しているコミュニティ
              %a.button_b.button_white_a.button_new_entry 新しいコミュニティに入る
            %ul.join_community_list
              %li.join_community_item
                %a
                  .box_community_item_img
                    %p image画像
                  %p.community_item_title ペンタトニックスが好き
                  %p.community_item_count 276人
            .box_community_pager
              %a.pager_pre.button_c.button_white_a.fa.fa-chevron-left
              %a.pager_next.button_c.button_white_a.fa.fa-chevron-right
          .box_mypage_introduction
            %p.introduction_title 自己紹介文
            %p.introduction_note 自己紹介文を充実させると、マッチング１０倍UP!!
            %p.introduction_text 本文

app/views/profiles/edit.haml
=render 'shared/header'
=render 'shared/side'
.wrapper
  =render 'user_profile_edit'
  =render 'shared/footer'

app/views/profiles/new.haml
=render 'shared/header'
=render 'shared/side'
.wrapper
  =render 'form'
  =render 'shared/footer'

app/views/profiles/show.haml
=render 'shared/header'
=render 'shared/side'
.wrapper
  =render 'user_profile'
  =render 'shared/footer'

app/views/search/index.haml
=render 'shared/header'
=render 'shared/side'
.wrapper
  =render 'shared/main'
  =render 'shared/footer'

app/views/shared/_footer.haml
%footer#main_footer
  .main_footer
    .foot-banner バナーだよ
    %nav
      %ul.float
        %li.footer_navi_item
          %a Pairsとは
        %li.footer_navi_item
          %a 幸せレポート
        %li.footer_navi_item
          %a 安心の常時監視体制
        %li.footer_navi_item
          %a 安心のセキュリティ
        %li.footer_navi_item
          %a ヘルプ
        %li.footer_navi_item
          %a お問い合わせ
      %ul.float
        %li.footer_navi_item
          %a 会社概要
        %li.footer_navi_item
          %a 利用規約
        %li.footer_navi_item
          %a プライバシーポリシー
        %li.footer_navi_item
          %a 特定商取引法に基づく表示
        %li.footer_navi_item
          %a 資金決済法に基づく表示
    .footer_label
      .footer_label_horizontal_box
        =image_tag "truste_ja.png"
        =image_tag "SSL.png",class: "right-img"
    %p.footer_approved インターネット異性紹介事業届出済み （受理番号1145141919）
    %small.footer_copyright (c) eureka, inc

app/views/shared/_header.haml
%header.main_header
  .box_header_inner
    =link_to image_tag("logo_pairs.png"),root_path
    %a.button_b.button_white_a=link_to "Facebookログイン", user_facebook_omniauth_authorize_path
    .header_logo
      %p.pairs_concept Facebookではじめる恋愛・結婚
      %i.fa.fa-comments-o
        %a.hide

app/views/shared/_main.haml
.ui-view
  .main.box_serch_view.contents_padding
    .box_notice_summary
      %ul.notice_list
        %li.notice_item
          %a Pairsからのお知らせが◯件あります
    .banner
      %p.banner__message バナー
    .box_search_menu
      .button_search_setting
        %a.button_b.button_white_a 
          %span 検索条件
      %p.search_result_count ◯人中 1~16人を表示
      %nav.box_change_view_tabs
        %ul.change_view_tabs
          %li.tab_item.tab_item01.is_current
          %li.tab_item.tab_item02
    .box_grid_header
      .box_grid_header01
        %p.header_display_label 表示人数
        .header_display_select
          %select.customSelect.button_white_a
            %option{value: "16"} 16人
            %option{value: "32"} 32人
            %option{value: "64"} 64人
            %option{value: "96"} 96人
            %option{value: "128"} 128人
      .box_grid_header03
        %span.total_like_number_desc いいねをあと
        %em
          %span 46人押しましょう！
      .box_grid_header02
        %button.button_b.button_white_a.button_show_pickup 今日のピックアップ
    .box_list_view_user
      %ul.list_view_users
        -@searches.each do |user|
          %li.list_view_user_item
            .box_user_photo
              =image_tag(user.image,size: "150x150")
            .box_user_info01
              %span.user_summary ●
              %span.user_area= user.birthplace
              %span.user_age= "#{user.age} 歳" 
            .box_user_info02
            .box_user_info03
              %i.fa.fa-thumbs-o-up 1
              %i.fa.fa-heart.user_chemistry 86%
            .user_tweet
              .user_tweet_body よろしくお願いします！
            =render "users/like_form", user: user
      =paginate @searches
      .box_like_remaining
        %p いいねをあと
        %em
          %span#total_like_numbers_footer 46人押せます！

app/views/shared/_side.haml
.side_contents
  .profile_summary
    .profile_photo
      =link_to image_tag(current_user.image,class: "side_image"),profile_path(current_user)
    .profile_name
      =link_to current_user.name,profile_path(current_user)
    .profile_status
      %p.is_free_member 無料会員
  .my_profile_input_rate
    %p.input_late_label プロフィール入力率 100%
    .input_rate_graph_value
      .is_percent_100
  .box_my_status
    %ul.my_status_list
      %li.my_status_item.leftover_like
        %p.status_label 残りのいいね数
        %p#total_like_numbers
          .stats_value
        %a#sidemenu_addlike.button_c.button_orange_a.link_more 追加する
      %li.my_status_item.leftover_point
        %p.status_label ポイント残高
        %p#total_point_numbers
          .stats_value
        %a#sidemenu_addlike.button_c.button_orange_a.link_more 追加する
  .box_my_private_mode
    .box_pm_state 
      .pm_state_image
        %p.pm_state_text プライベートモードがOFFになっています。
      .link_pm_setting
        %a プライベートモードとは？
  .box_gnavi
    .box_gnavis01
      %ul
        %li.gnavi_item
          %a さがす
        %li.gnavi_item
          %a お相手をさがす
    .box_gnavis02
      %ul
        %li.gnavi_item
          %a いいね
        %li.gnavi_item
          %a 相手からのいいね！
        %li.gnavi_item
          %a 自分からのいいね！
        %li.gnavi_item
          %a お気に入り
    .box_gnavis03
      %ul
        %li.gnavi_item
          %a コミュニティ
        %li.gnavi_item
          %a コミュニティを探す
    .box_gnavis04
      %ul
        %li.gnavi_item
          %a 有料サービス
        %li.gnavi_item
          %a 有料会員とは？
        %li.gnavi_item
          %a プレミアムオプション
        %li.gnavi_item
          %a Pairsポイント
    .box_gnavis05
      %ul
        %li.gnavi_item
          %a 足あと
        %li.gnavi_item
          %a 足あと
    .box_gnavis06
      %ul
        %li.gnavi_item
          %a 各種設定
        %li.gnavi_item
          %a 通知/いいね上限
        %li.gnavi_item
          %a Facebook友達更新
        %li.gnavi_item
          %a 非表示・ブロック
        %li.gnavi_item
          %a オフラインモード設定
    .box_gnavis07
      %ul
        %li.gnavi_item
          %a 初めての方へ
        %li.gnavi_item
          %a 男性会員限定
        %li.gnavi_item
          %a ヘルプ

app/views/users/_like_form.haml
#like_form
  -if current_user.liking?(user)
    %button.button_white_a "見てね"
  -else
    =form_for(current_user.liking_likes.build(liking_id: user.id)) do |f|
      = f.hidden_field :liking_id
      = f.submit "いいね", class: "button_white_a"